import type { ProtoOADayOfWeek } from "../enums/ProtoOADayOfWeek.ts";
import type { ProtoOAInterval } from "./ProtoOAInterval.ts";
import type { ProtoOACommissionType } from "../enums/ProtoOACommissionType.ts";
import type { ProtoOASymbolDistanceType } from "../enums/ProtoOASymbolDistanceType.ts";
import type { ProtoOAMinCommissionType } from "../enums/ProtoOAMinCommissionType.ts";
import type { ProtoOATradingMode } from "../enums/ProtoOATradingMode.ts";
import type { ProtoOASwapCalculationType } from "../enums/ProtoOASwapCalculationType.ts";
import type { ProtoOAHoliday } from "./ProtoOAHoliday.ts";
import type { BaseMessage } from "./BaseMessage.ts";

export interface ProtoOASymbol extends BaseMessage {
  symbolId: number;
  digits: number;
  pipPosition: number;
  enableShortSelling?: boolean;
  guaranteedStopLoss?: boolean;
  swapRollover3Days?: ProtoOADayOfWeek;
  swapLong?: number;
  swapShort?: number;
  maxVolume?: number;
  minVolume?: number;
  stepVolume?: number;
  maxExposure?: number;
  schedule?: ReadonlyArray<ProtoOAInterval>;
  commission?: number;
  commissionType?: ProtoOACommissionType;
  slDistance?: number;
  tpDistance?: number;
  gslDistance?: number;
  gslCharge?: number;
  distanceSetIn?: ProtoOASymbolDistanceType;
  minCommission?: number;
  minCommissionType?: ProtoOAMinCommissionType;
  minCommissionAsset?: string;
  rolloverCommission?: number;
  skipRolloverDays?: number;
  scheduleTimeZone?: string;
  tradingMode?: ProtoOATradingMode;
  rolloverCommission3Days?: ProtoOADayOfWeek;
  swapCalculationType?: ProtoOASwapCalculationType;
  lotSize?: number;
  preciseTradingCommissionRate?: number;
  preciseMinCommission?: number;
  holiday?: ReadonlyArray<ProtoOAHoliday>;
  pnlConversionFeeRate?: number;
  leverageId?: number;
  swapPeriod?: number;
  swapTime?: number;
  skipSWAPPeriods?: number;
  chargeSwapAtWeekends?: boolean;
  measurementUnits?: string;
}
