// code generated by pbf v4.0.1

export const ProtoPayloadType = {
    "PROTO_MESSAGE": 5,
    "ERROR_RES": 50,
    "HEARTBEAT_EVENT": 51
};

export const ProtoErrorCode = {
    "UNKNOWN_ERROR": 1,
    "UNSUPPORTED_MESSAGE": 2,
    "INVALID_REQUEST": 3,
    "TIMEOUT_ERROR": 5,
    "ENTITY_NOT_FOUND": 6,
    "CANT_ROUTE_REQUEST": 7,
    "FRAME_TOO_LONG": 8,
    "MARKET_CLOSED": 9,
    "CONCURRENT_MODIFICATION": 10,
    "BLOCKED_PAYLOAD_TYPE": 11
};

export function readProtoMessage(pbf, end) {
    return pbf.readFields(readProtoMessageField, {payloadType: 0, payload: undefined, clientMsgId: ""}, end);
}
function readProtoMessageField(tag, obj, pbf) {
    if (tag === 1) obj.payloadType = pbf.readVarint();
    else if (tag === 2) obj.payload = pbf.readBytes();
    else if (tag === 3) obj.clientMsgId = pbf.readString();
}
export function writeProtoMessage(obj, pbf) {
    if (obj.payloadType) pbf.writeVarintField(1, obj.payloadType);
    if (obj.payload != null) pbf.writeBytesField(2, obj.payload);
    if (obj.clientMsgId) pbf.writeStringField(3, obj.clientMsgId);
}

export function readProtoErrorRes(pbf, end) {
    return pbf.readFields(readProtoErrorResField, {payloadType: 50, errorCode: "", description: "", maintenanceEndTimestamp: 0}, end);
}
function readProtoErrorResField(tag, obj, pbf) {
    if (tag === 1) obj.payloadType = pbf.readVarint();
    else if (tag === 2) obj.errorCode = pbf.readString();
    else if (tag === 3) obj.description = pbf.readString();
    else if (tag === 4) obj.maintenanceEndTimestamp = pbf.readVarint();
}
export function writeProtoErrorRes(obj, pbf) {
    if (obj.payloadType != null && obj.payloadType !== 50) pbf.writeVarintField(1, obj.payloadType);
    if (obj.errorCode) pbf.writeStringField(2, obj.errorCode);
    if (obj.description) pbf.writeStringField(3, obj.description);
    if (obj.maintenanceEndTimestamp) pbf.writeVarintField(4, obj.maintenanceEndTimestamp);
}

export function readProtoHeartbeatEvent(pbf, end) {
    return pbf.readFields(readProtoHeartbeatEventField, {payloadType: 51}, end);
}
function readProtoHeartbeatEventField(tag, obj, pbf) {
    if (tag === 1) obj.payloadType = pbf.readVarint();
}
export function writeProtoHeartbeatEvent(obj, pbf) {
    if (obj.payloadType != null && obj.payloadType !== 51) pbf.writeVarintField(1, obj.payloadType);
}
