// code generated by pbf v4.0.1

export const ProtoPayloadType = {
    "PROTO_MESSAGE": 5,
    "ERROR_RES": 50,
    "HEARTBEAT_EVENT": 51
};

export const ProtoErrorCode = {
    "UNKNOWN_ERROR": 1,
    "UNSUPPORTED_MESSAGE": 2,
    "INVALID_REQUEST": 3,
    "TIMEOUT_ERROR": 5,
    "ENTITY_NOT_FOUND": 6,
    "CANT_ROUTE_REQUEST": 7,
    "FRAME_TOO_LONG": 8,
    "MARKET_CLOSED": 9,
    "CONCURRENT_MODIFICATION": 10,
    "BLOCKED_PAYLOAD_TYPE": 11
};
