name: Deploy to NPM

on: [release]

jobs:
  deploy:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - run: npm install
    - run: npm test
    - run: npm publish --access public
      env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_DEPLOY_TOKEN }}
