name: Deploy to NPM

on:
  push:
    branches: # Array of patterns that match refs/heads
      - master # Push events on master branch
    tags: # Array of patterns that match refs/tags.
      - v* # Push events to v1 tag

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: npm install
      - run: npm test
      - run: npm publish --access public
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_DEPLOY_TOKEN }}
